name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Ruff
        uses: astral-sh/ruff-action@v1

      - name: Format
        run: ruff format ./src

      - name: Lint
        run: ruff check ./src --fix
